### ISSUE TITLE
Opening furnace when locked and interacting with the GUI closes it

### ISSUE THREAD

**Issue by turtledude01** [IchorDev/Latch#5] opened 2017-01-27 20:46 UTC
Ok, so a user on my server recently let me know that they kept getting kicked out of the GUI of all furnaces every time they tried to place an item in to smelt.  The furnace worked fine, but they got kicked out immediately after placing or removing items.  I had them /latch delete on it and the furnace went back to normal functionality and not closing on every interaction.

**Comment by parlough** [comment] 2017-01-27 23:48
I cannot reproduce this. If any more players have this issue or you have any information please respond here. I will not close it for now as I will continue to investigate.

**Comment by turtledude01** [comment] 2017-01-30 15:25
Seems that shift clicking items out of a locked furnace makes them dissapear

**Comment by parlough** [comment] 2017-01-30 16:08
@turtledude01 What version and build of Sponge are using? There's been a lot of changes recently in Sponge relating to inventory recently so this stuff is fairly volatile.

**Comment by turtledude01** [comment] 2017-01-30 16:19
Spongevanilla one of the newest API 6 builds

**Comment by parlough** [comment] 2017-02-09 23:43
I have not been able to reproduce this issue and @turtledude01 has told me he is not experiencing it anymore either. So I will close this for now, but if anyone else experiences it please feel free to comment.

**Closed as completed by parlough** 2017-02-09 23:43 UTC
Labels: bug, needs verification
